'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');

const vendorSync = require('../scripts/vendor-giseldah-calcstat');

test('default source URL is pinned to a specific commit ref', function () {
  assert.match(vendorSync.DEFAULT_REF, /^[0-9a-f]{40}$/);
  assert.equal(
    vendorSync.buildSourceUrl(vendorSync.DEFAULT_REF),
    'https://raw.githubusercontent.com/Giseldah/Giseldah.github.io/' + vendorSync.DEFAULT_REF + '/js/calcstat.js'
  );
});

test('loadSource keeps the existing vendored copy when fetch fails', async function () {
  var loaded = await vendorSync.loadSource({
    sourceUrl: vendorSync.buildSourceUrl(vendorSync.DEFAULT_REF),
    targetPath: 'ignored-target.js',
    existsSync: function () { return true; },
    fetchImpl: async function () {
      throw new Error('network unavailable');
    },
  });

  assert.equal(loaded.source, null);
  assert.equal(loaded.sourceLabel, 'ignored-target.js');
  assert.match(loaded.warning, /network unavailable/);
});

test('buildVendoredFile appends CommonJS exports to the upstream source', function () {
  var output = vendorSync.buildVendoredFile(
    'function CalcStat() {}\nconst DblCalcDev = 1;',
    vendorSync.buildSourceUrl(vendorSync.DEFAULT_REF)
  );

  assert.match(output, /Generated by scripts\/vendor-giseldah-calcstat\.js/);
  assert.match(output, /exports\.CalcStat = CalcStat;/);
  assert.match(output, /exports\.DblCalcDev = DblCalcDev;/);
});
