/**
 * DO Function: /api/quests/lookup
 *
 * Quest search and lookup API. Uses a lightweight quest index (id/name/level)
 * bundled at build time (quest-index.json, generated by npm run build).
 *
 * Endpoints:
 *   GET /api/quests/lookup?q=name     – search by name (min 2 chars), returns up to 50 matches
 *   GET /api/quests/lookup?id=...     – check if a single quest ID has map overlay data
 *
 * quest-index.json is committed to git so it is available at function deploy time.
 * Regenerate it by running `npm run build` in the project root and committing the result.
 */

const questIndex = require('./quest-index.json');

// Pre-build lowercase name array once at cold-start for fast substring search
const questNames = questIndex.map(q => (q.n || '').toLowerCase());

const CORS_HEADERS = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': 'https://lotroguides.com',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Cache-Control': 'public, max-age=3600, stale-while-revalidate=300',
};

exports.main = async function main(args) {
  if (args.__ow_method === 'options') {
    return { statusCode: 204, headers: CORS_HEADERS };
  }

  if (args.__ow_method && args.__ow_method !== 'get') {
    return { statusCode: 405, headers: CORS_HEADERS, body: { error: 'Method not allowed' } };
  }

  // Single ID existence check — used by map to verify quest has overlay data
  const id = args.id;
  if (id) {
    const idx = questIndex.findIndex(q => q.id === String(id));
    if (idx === -1) {
      return { statusCode: 404, headers: CORS_HEADERS, body: { error: 'Quest not found' } };
    }
    return { statusCode: 200, headers: CORS_HEADERS, body: questIndex[idx] };
  }

  // Name search
  const q = (args.q || '').trim().toLowerCase();
  if (q.length < 2) {
    return {
      statusCode: 400,
      headers: CORS_HEADERS,
      body: { error: 'Query must be at least 2 characters', results: [] },
    };
  }

  const limit = Math.min(parseInt(args.limit, 10) || 20, 50);
  const lvMin = args.lv_min ? parseInt(args.lv_min, 10) : 0;
  const lvMax = args.lv_max ? parseInt(args.lv_max, 10) : 999;

  const results = [];
  for (let i = 0; i < questNames.length && results.length < limit; i++) {
    if (!questNames[i].includes(q)) continue;
    const entry = questIndex[i];
    if (lvMin > 0 && (entry.lv || 0) < lvMin) continue;
    if (lvMax < 999 && (entry.lv || 0) > lvMax) continue;
    results.push(entry);
  }

  return {
    statusCode: 200,
    headers: CORS_HEADERS,
    body: { results, total: results.length, q },
  };
};
