name: lotroguides
static_sites:
  - name: lotroguides-web
    github:
      repo: djburkhart/lotroguides.com
      branch: main
    build_command: npm run build
    output_dir: /
    environment_slug: node-js
    routes:
      - path: /
    envs:
      - key: GOOGLE_ADSENSE_ACCOUNT
        type: SECRET
        scope: BUILD_TIME
      - key: GOOGLE_ANALYTICS_ID
        type: SECRET
        scope: BUILD_TIME
      - key: GOOGLE_TAG_MANAGER_ID
        type: SECRET
        scope: BUILD_TIME
      - key: GOOGLE_OAUTH_CLIENT_ID
        type: SECRET
        scope: BUILD_TIME
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        type: SECRET
        scope: BUILD_TIME
      - key: EDITOR_ALLOWED_EMAILS
        type: SECRET
        scope: BUILD_TIME
      - key: GITHUB_REPO
        type: SECRET
        scope: BUILD_TIME
      - key: GITHUB_CLIENT_ID
        type: SECRET
        scope: BUILD_TIME
      - key: DO_CDN_URL
        type: SECRET
        scope: BUILD_TIME
functions:
  - name: github-auth
    github:
      repo: djburkhart/lotroguides.com
      branch: main
    source_dir: packages
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: GITHUB_CLIENT_ID
        type: SECRET
      - key: GITHUB_CLIENT_SECRET
        type: SECRET
      - key: RECAPTCHA_SECRET_KEY
        type: SECRET
      - key: RECAPTCHA_SITE_KEY
        type: SECRET
      - key: GOOGLE_CLOUD_PROJECT
        type: SECRET
      - key: GOOGLE_OAUTH_CLIENT_ID
        type: SECRET
      - key: DISCORD_PUBLIC_KEY
        type: SECRET
      - key: DISCORD_APP_ID
        type: SECRET
      - key: DISCORD_BOT_TOKEN
        type: SECRET
      - key: DO_CDN_URL
        type: SECRET
      - key: SITE_API_URL
        type: SECRET
      - key: DO_SPACES_KEY
        type: SECRET
      - key: DO_SPACES_SECRET
        type: SECRET
      - key: DO_SPACES_BUCKET
        type: SECRET
      - key: DO_SPACES_REGION
        type: SECRET
