name: lotroguides
static_sites:
  - name: lotroguides-web
    github:
      repo: djburkhart/lotroguides.com
      branch: main
    build_command: npm run build
    output_dir: /
    environment_slug: node-js
    envs:
      - key: GOOGLE_ADSENSE_ACCOUNT
        type: SECRET
        scope: BUILD_TIME
      - key: GOOGLE_ANALYTICS_ID
        type: SECRET
        scope: BUILD_TIME
      - key: GOOGLE_TAG_MANAGER_ID
        type: SECRET
        scope: BUILD_TIME
