#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════════
   CDN Sync — Upload large binary assets to DigitalOcean Spaces
   Skips files whose remote ETag already matches the local MD5.
   Run:  node scripts/sync-cdn.js
   Flags: --all   force re-upload every file regardless of ETag
   Required env vars: DO_SPACES_KEY, DO_SPACES_SECRET, DO_SPACES_BUCKET
   Optional env vars: DO_SPACES_REGION (default: nyc3)
   ═══════════════════════════════════════════════════════════════════════════ */
'use strict';

require('dotenv').config();

const { S3Client, ListObjectsV2Command, PutObjectCommand } = require('@aws-sdk/client-s3');
const fs   = require('fs');
const path = require('path');
const crypto = require('crypto');
const zlib = require('zlib');

// ── Config ──────────────────────────────────────────────────────────────────
const KEY    = process.env.DO_SPACES_KEY;
const SECRET = process.env.DO_SPACES_SECRET;
const BUCKET = process.env.DO_SPACES_BUCKET;
const REGION = process.env.DO_SPACES_REGION || 'nyc3';
const FORCE  = process.argv.includes('--all');

if (!KEY || !SECRET || !BUCKET) {
  console.error('Error: Missing required env vars (DO_SPACES_KEY, DO_SPACES_SECRET, DO_SPACES_BUCKET).');
  console.error('Copy .env.example to .env and fill in your DigitalOcean Spaces credentials.');
  process.exit(1);
}

const client = new S3Client({
  endpoint:        `https://${REGION}.digitaloceanspaces.com`,
  region:          REGION,
  credentials:     { accessKeyId: KEY, secretAccessKey: SECRET },
  forcePathStyle:  false,
});

// ── Directories to sync (relative to project root) ─────────────────────────
// Note: data/content/ is gitignored/not generated by build — safe to list 'data' broadly.
const DIRS_TO_SYNC = ['img/maps/basemaps', 'img/icons', 'data'];

// ── MIME type map ───────────────────────────────────────────────────────────
const MIME = {
  '.webp': 'image/webp',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif':  'image/gif',
  '.svg':  'image/svg+xml',
  '.json': 'application/json',
};

function getMime(filePath) {
  return MIME[path.extname(filePath).toLowerCase()] || 'application/octet-stream';
}

function md5hex(buf) {
  return crypto.createHash('md5').update(buf).digest('hex');
}

// ── List all objects in the bucket (paginated) ─────────────────────────────
async function listAllObjects() {
  const map = {};
  let token;
  do {
    const res = await client.send(new ListObjectsV2Command({
      Bucket: BUCKET,
      ContinuationToken: token,
    }));
    for (const obj of (res.Contents || [])) {
      // S3 ETags are returned with surrounding quotes — strip them
      map[obj.Key] = (obj.ETag || '').replace(/"/g, '');
    }
    token = res.NextContinuationToken;
  } while (token);
  return map;
}

// ── Recursively collect file paths ─────────────────────────────────────────
function scanDir(dir) {
  const files = [];
  if (!fs.existsSync(dir)) return files;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...scanDir(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

// ── Main ────────────────────────────────────────────────────────────────────
async function main() {
  const root = path.join(__dirname, '..');

  console.log(FORCE ? 'Force mode: uploading all files.' : 'Checking remote ETags…');
  const remoteEtags = FORCE ? {} : await listAllObjects();
  const remoteCount = Object.keys(remoteEtags).length;
  if (!FORCE) console.log(`  ${remoteCount} objects already on bucket.`);

  // Collect local files
  const localFiles = [];
  for (const dir of DIRS_TO_SYNC) {
    const abs = path.join(root, dir);
    const found = scanDir(abs);
    for (const f of found) {
      const key = path.relative(root, f).replace(/\\/g, '/');
      localFiles.push({ key, abs: f });
    }
  }
  console.log(`Scanning ${localFiles.length} local files across: ${DIRS_TO_SYNC.join(', ')}`);

  let uploaded = 0;
  let skipped  = 0;
  let failed   = 0;

  for (const { key, abs } of localFiles) {
    const buf      = fs.readFileSync(abs);
    const localMd5 = md5hex(buf);

    if (!FORCE && remoteEtags[key] === localMd5) {
      skipped++;
      continue;
    }

    try {
      process.stdout.write(`  ↑ ${key} … `);
      await client.send(new PutObjectCommand({
        Bucket:       BUCKET,
        Key:          key,
        Body:         buf,
        ContentType:  getMime(abs),
        ACL:          'public-read',
        CacheControl: 'public, max-age=31536000, immutable',
      }));
      console.log('ok');
      uploaded++;
    } catch (err) {
      console.log('FAILED: ' + err.message);
      failed++;
    }
  }

  console.log(`\nComplete: ${uploaded} uploaded, ${skipped} already up to date, ${failed} failed.`);

  // ── Bundle data/lore/ as a single gzipped archive for build-time download ──
  const loreDir = path.join(root, 'data', 'lore');
  if (fs.existsSync(loreDir)) {
    process.stdout.write('\nBundling data/lore/ → data-lore-bundle.json.gz … ');
    const bundle = {};
    const loreFiles = scanDir(loreDir);
    for (const f of loreFiles) {
      const key = path.relative(path.join(root, 'data'), f).replace(/\\/g, '/');
      bundle[key] = fs.readFileSync(f, 'utf8');
    }
    const json = JSON.stringify(bundle);
    const gzipped = zlib.gzipSync(Buffer.from(json, 'utf8'), { level: 9 });
    console.log(`${(json.length / 1024 / 1024).toFixed(1)} MB → ${(gzipped.length / 1024 / 1024).toFixed(1)} MB gzipped`);

    const bundleKey = 'data-lore-bundle.json.gz';
    const bundleMd5 = md5hex(gzipped);
    if (!FORCE && remoteEtags[bundleKey] === bundleMd5) {
      console.log(`  ✓ ${bundleKey} (already up to date)`);
    } else {
      try {
        process.stdout.write(`  ↑ ${bundleKey} … `);
        await client.send(new PutObjectCommand({
          Bucket:       BUCKET,
          Key:          bundleKey,
          Body:         gzipped,
          ContentType:  'application/gzip',
          ACL:          'public-read',
          CacheControl: 'public, max-age=86400',
        }));
        console.log('ok');
      } catch (err) {
        console.log('FAILED: ' + err.message);
        failed++;
      }
    }
  }

  if (failed > 0) process.exit(1);
}

main().catch(err => {
  console.error('Sync failed:', err.message);
  process.exit(1);
});
