packages:
  - name: github
    functions:
      - name: auth
        runtime: nodejs:22
        web: true
  - name: cdn
    functions:
      - name: upload
        runtime: nodejs:22
        web: true
  - name: quests
    functions:
      - name: lookup
        runtime: nodejs:22
        web: true
  - name: recaptcha
    functions:
      - name: verify
        runtime: nodejs:22
        web: true
  - name: builds
    functions:
      - name: save
        runtime: nodejs:22
        web: true
  - name: cusdis
    functions:
      - name: webhook
        runtime: nodejs:22
        web: true
