packages:
  - name: github
    functions:
      - name: auth
        runtime: nodejs:20
        web: true
  - name: quests
    functions:
      - name: lookup
        runtime: nodejs:20
        web: true
